#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
# Personal environment overrides, such as MANPATH, TERM, fpath (non interactive scripts should have their environment completly set up here). Preferred $LOCALE, $LANG, readlne config, cdpath, session managers, additional fpath user functions, login shells (but non necessarily ineractive as when invoked via ssh remote cmd ) will read config up to this point

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export VISUAL='nano'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  ~/Code/Work/lendinghome-monolith/toolbelt
  ~/Code/Work/lendinghome-monolith/bin
  ~/.rbenv/shims
  /usr/local/{bin,sbin}
  ~/.bin
  $path
)

# Load additional shell functions
fpath=(usr/local/share/zsh/site-functions $fpath)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi
