#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
# User customization of their interactive environment for terminals. Sourcing custom shell additions (gcloud.comp.inc), custom user frameworks (zprezto is invoked here), additional path required by custom software installed in /opt/

# Profile startup
# zmodload zsh/zprof

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

source ~/.zsh/aliases
source ~/.zsh/fzf

if [[ -s ~/.zsh/private ]]; then
  source ~/.zsh/private
fi

for function in ~/.zsh/functions/*; do
  source $function
done

# Move and rename with regex http://zshwiki.org/home/builtin/functions/zmv
autoload -U zmv

autoload -Uz bracketed-paste-magic
zle -N bracketed-paste bracketed-paste-magic

source /usr/local/opt/asdf/asdf.sh
# source /usr/local/opt/asdf/completions/asdf.bash

# Tab completion for serverless
serverless_completions=('serverless' 'sls')

for pkg in serverless_completions; do
  comp_file="~/.config/yarn/global/node_modules/tabtab/.completions/$pkg.zsh"

  [[ -f $comp_file ]] && source $comp_file
done

source ~/.zprezto/modules/prompt/external/async/async.zsh
async_init
source ~/.zsh/add_yarn_to_path

# Profile startup
# zprof
